/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int LESS = 7;
  /** RegularExpression Id. */
  int GREATER = 8;
  /** RegularExpression Id. */
  int LESSEQ = 9;
  /** RegularExpression Id. */
  int GREATEREQ = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int NOT_EQUAL = 12;
  /** RegularExpression Id. */
  int Num = 13;
  /** RegularExpression Id. */
  int Bool = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int TIMES = 17;
  /** RegularExpression Id. */
  int DIV = 18;
  /** RegularExpression Id. */
  int LPAR = 19;
  /** RegularExpression Id. */
  int RPAR = 20;
  /** RegularExpression Id. */
  int LET = 21;
  /** RegularExpression Id. */
  int IN = 22;
  /** RegularExpression Id. */
  int ATTR = 23;
  /** RegularExpression Id. */
  int DOTCOMMA = 24;
  /** RegularExpression Id. */
  int TWODOTS = 25;
  /** RegularExpression Id. */
  int ASSIGN = 26;
  /** RegularExpression Id. */
  int DEREFERENCE = 27;
  /** RegularExpression Id. */
  int NEW = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int END = 31;
  /** RegularExpression Id. */
  int PRINT = 32;
  /** RegularExpression Id. */
  int PRINTLN = 33;
  /** RegularExpression Id. */
  int IF = 34;
  /** RegularExpression Id. */
  int THEN = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int NEGATE = 37;
  /** RegularExpression Id. */
  int FN = 38;
  /** RegularExpression Id. */
  int ARROW = 39;
  /** RegularExpression Id. */
  int COMMA = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;
  /** RegularExpression Id. */
  int ID = 44;
  /** RegularExpression Id. */
  int LETTER = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "<Num>",
    "<Bool>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"let\"",
    "\"in\"",
    "\"=\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"!\"",
    "\"new\"",
    "\"while\"",
    "\"do\"",
    "\"end\"",
    "\"print\"",
    "\"println\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"~\"",
    "\"fn\"",
    "\"->\"",
    "\",\"",
    "<STRING>",
    "<INT>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
  };

}
