/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EL = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int LESS = 7;
  /** RegularExpression Id. */
  int GREATER = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int NEGATION = 10;
  /** RegularExpression Id. */
  int NOT_EQUAL = 11;
  /** RegularExpression Id. */
  int Num = 12;
  /** RegularExpression Id. */
  int Bool = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int MINUS = 15;
  /** RegularExpression Id. */
  int TIMES = 16;
  /** RegularExpression Id. */
  int DIV = 17;
  /** RegularExpression Id. */
  int LPAR = 18;
  /** RegularExpression Id. */
  int RPAR = 19;
  /** RegularExpression Id. */
  int LET = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int ATTR = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int ID = 25;
  /** RegularExpression Id. */
  int LETTER = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!\"",
    "\"!=\"",
    "<Num>",
    "<Bool>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"let\"",
    "\"in\"",
    "\"=\"",
    "<INT>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
  };

}
